export const CODES = Object.freeze({
  BAD_REQUEST: 'BAD_REQUEST',
  NOT_FOUND: 'NOT_FOUND',
  LEDGER_NOT_FOUND: 'LEDGER_NOT_FOUND',
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  CATEGORY_SLUG_CONFLICT: 'CATEGORY_SLUG_CONFLICT',
  CATEGORY_INVALID_NAME: 'CATEGORY_INVALID_NAME',
  RATE_LIMIT: 'RATE_LIMIT',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  CHAT_UNAVAILABLE: 'CHAT_UNAVAILABLE',
  CHAT_BAD_RESPONSE: 'CHAT_BAD_RESPONSE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
});
